# Generated by Django 4.2.7 on 2024-01-03 07:18

from django.db import migrations, models
import v2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=v2.models.hashname)),
                ('model', models.CharField(default='geometry.humanoid.customSlim', max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SkinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin', models.ManyToManyField(blank=True, related_name='cont', to='v2.skin')),
            ],
        ),
    ]
