# Generated by Django 4.2.7 on 2024-01-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_alter_skin_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
