# Generated by Django 4.2.7 on 2024-01-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0003_alter_skin_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinlist',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
