# Generated by Django 4.2.7 on 2024-01-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0004_skinlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinlist',
            name='name',
            field=models.CharField(default='skinpack', max_length=30),
        ),
    ]
