# Generated by Django 4.2.7 on 2024-01-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0005_skinlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='file',
            field=models.ImageField(upload_to='C:\\Users\\A\\Desktop\\webdesign\\Lesson_7\\skincompress\\v2\\skins'),
        ),
    ]
